In [1]:
import pandas as pd
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report
from sklearn.naive_bayes import MultinomialNB
from sklearn.linear_model import SGDClassifier

In [21]:
data = pd.DataFrame([("i love spending time with my friends and family", "positive"),
                    ("that was the best meal i've ever had in my life", "positive"),
                    ("i feel so grateful for everything i have in my life", "positive"),
                    ("i received a promotion at work and i couldn't be happier", "positive"),
                    ("watching a beautiful sunset always fills me with joy", "positive"),
                    ("my partner surprised me with a thoughtful gift and it made my day", "positive"),
                    ("i am so proud of my daughter for graduating with honors", "positive"),
                    ("listening to my favorite music always puts me in a good mood", "positive"),
                    ("i love the feeling of accomplishment after completing a challenging task", "positive"),
                    ("i am excited to go on vacation next week", "positive"),
                    ("i feel so overwhelmed with work and responsibilities", "negative"),
                    ("the traffic during my commute is always so frustrating", "negative"),
                    ("i received a parking ticket and it ruined my day", "negative"),
                    ("i got into an argument with my partner and we're not speaking", "negative"),
                    ("i have a headache and i feel terrible", "negative"),
                    ("i received a rejection letter for the job i really wanted", "negative"),
                    ("my car broke down and it's going to be expensive to fix", "negative"),
                    ("i'm feeling sad because i miss my friends who live far away", "negative"),
                    ("i'm frustrated because i can't seem to make progress on my project", "negative"),
                    ("i'm disappointed because my team lost the game", "negative")
                    ],
                    columns = ['text', 'sentiment'])

In [12]:
data

                                                 text sentiment
0     i love spending time with my friends and family  positive
1     that was the best meal i've ever had in my life  positive
2   i feel so grateful for everything i have in my...  positive
3   i received a promotion at work and i couldn't ...  positive
4   watching a beautiful sunset always fills me wi...  positive
5   my partner surprised me with a thoughtful gift...  positive
6   i am so proud of my daughter for graduating wi...  positive
7   listening to my favorite music always puts me ...  positive
8   i love the feeling of accomplishment after com...  positive
9            i am excited to go on vacation next week  positive
10  i feel so overwhelmed with work and responsibi...  negative
11  the traffic during my commute is always so fru...  negative
12   i received a parking ticket and it ruined my day  negative
13  i got into an argument with my partner and we'...  negative
14              i have a headache and i feel terrible  negative
15  i received a rejection letter for the job i re...  negative
16  my car broke down and it's going to be expensi...  negative
17  i'm feeling sad because i miss my friends who ...  negative
18  i'm frustrated because i can't seem to make pr...  negative
19     i'm disappointed because my team lost the game  negative

In [22]:
data = data.sample(frac = 1).reset_index(drop = True)

In [23]:
data

                                                 text sentiment
0   listening to my favorite music always puts me ...  positive
1   my partner surprised me with a thoughtful gift...  positive
2   i feel so overwhelmed with work and responsibi...  negative
3     i love spending time with my friends and family  positive
4   i love the feeling of accomplishment after com...  positive
5   i received a rejection letter for the job i re...  negative
6   the traffic during my commute is always so fru...  negative
7   i am so proud of my daughter for graduating wi...  positive
8               i have a headache and i feel terrible  negative
9   i got into an argument with my partner and we'...  negative
10    that was the best meal i've ever had in my life  positive
11  i'm frustrated because i can't seem to make pr...  negative
12  my car broke down and it's going to be expensi...  negative
13   i received a parking ticket and it ruined my day  negative
14  i'm feeling sad because i miss my friends who ...  negative
15  i received a promotion at work and i couldn't ...  positive
16     i'm disappointed because my team lost the game  negative
17           i am excited to go on vacation next week  positive
18  watching a beautiful sunset always fills me wi...  positive
19  i feel so grateful for everything i have in my...  positive

In [7]:
X = data['text']
y = data['sentiment']

In [8]:
countvec = CountVectorizer()
countvec_fit = countvec.fit_transform(X)

In [9]:
bag_of_words = pd.DataFrame(countvec_fit.toarray(), columns = countvec.get_feature_names_out())

In [10]:
bag_of_words

    accomplishment  after  always  am  an  and  argument  at  ...  wanted  was  watching  we  week  who  with  work
0                0      0       0   0   0    0         0   0  ...       0    0         0   0     0    1     0     0
1                0      0       0   0   0    1         0   0  ...       0    0         0   0     0    0     1     1
2                0      0       1   0   0    0         0   0  ...       0    0         0   0     0    0     0     0
3                0      0       0   1   0    0         0   0  ...       0    0         0   0     0    0     1     0
4                0      0       0   0   0    1         0   0  ...       0    0         0   0     0    0     0     0
5                0      0       0   0   0    0         0   0  ...       0    1         0   0     0    0     0     0
6                0      0       0   0   0    1         0   0  ...       0    0         0   0     0    0     0     0
7                0      0       0   0   1    1         1   0  ...       0    0         0   1     0    0     1     0
8                0      0       0   0   0    1         0   0  ...       0    0         0   0     0    0     0     0
9                0      0       0   0   0    1         0   1  ...       0    0         0   0     0    0     0     1
10               0      0       0   0   0    0         0   0  ...       0    0         0   0     0    0     0     0
11               0      0       0   0   0    1         0   0  ...       0    0         0   0     0    0     1     0
12               1      1       0   0   0    0         0   0  ...       0    0         0   0     0    0     0     0
13               0      0       0   0   0    0         0   0  ...       1    0         0   0     0    0     0     0
14               0      0       1   0   0    0         0   0  ...       0    0         1   0     0    0     1     0
15               0      0       0   1   0    0         0   0  ...       0    0         0   0     1    0     0     0
16               0      0       0   0   0    1         0   0  ...       0    0         0   0     0    0     1     0
17               0      0       1   0   0    0         0   0  ...       0    0         0   0     0    0     0     0
18               0      0       0   0   0    0         0   0  ...       0    0         0   0     0    0     0     0
19               0      0       0   0   0    0         0   0  ...       0    0         0   0     0    0     0     0

[20 rows x 118 columns]

In [18]:
X_train, X_test, y_train, y_test = train_test_split(bag_of_words, y, test_size = 0.3, random_state = 7)

In [19]:
lr = LogisticRegression(random_state = 1).fit(X_train, y_train)

In [20]:
y_pred_lr = lr.predict(X_test)

In [23]:
accuracy_score(y_pred_lr, y_test)

0.5

In [24]:
print(classification_report(y_test, y_pred_lr, zero_division = 0))

              precision    recall  f1-score   support

    negative       0.50      0.33      0.40         3
    positive       0.50      0.67      0.57         3

    accuracy                           0.50         6
   macro avg       0.50      0.50      0.49         6
weighted avg       0.50      0.50      0.49         6

In [26]:
# Naive Bayes

In [27]:
nb = MultinomialNB().fit(X_train, y_train)

In [29]:
y_pred_nb = nb.predict(X_test)

In [30]:
accuracy_score(y_pred_nb, y_test)

0.5

In [32]:
classification_report(y_test, y_pred_nb, zero_division = 0)

'              precision    recall  f1-score   support\n\n    negative       0.50      0.33      0.40         3\n    positive       0.50      0.67      0.57         3\n\n    accuracy                           0.50         6\n   macro avg       0.50      0.50      0.49         6\nweighted avg       0.50      0.50      0.49         6\n'

In [34]:
# SVM

In [35]:
svm = SGDClassifier().fit(X_train, y_train)

In [36]:
y_pred_svm = svm.predict(X_test)